services:
    # implicit specification of what kind of repo I need here.
    # for tests it's overwritten with fake client
    SleeperBundle\Infrastructure\ElasticsearchGateway:
        arguments:
            - '@http.fake_client'
