services:
    SleeperBundle\:
        resource: '../../../../src/SleeperBundle/*'
        exclude: '../../../../src/SleeperBundle/Domain/Model'

    SleeperBundle\Infrastructure\Repository\DatabaseSleepRepository:
        factory: ["@doctrine", getRepository]
        arguments:
            - "SleeperBundle:SleepEntity"
