services:
#    sleeper.example:
#        class: SleeperBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    SleeperBundle\Controller\AnalyzerController:
        arguments:
            $logger: "@logger"
