services:

    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    SleeperBundle\:
        resource: '../../../../src/SleeperBundle/*'
        exclude: '../../../../src/SleeperBundle/Domain/Entity'

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    SleeperBundle\Application\Controller\:
        resource: '../../../../src/SleeperBundle/Application/Controller'
        tags: ['controller.service_arguments']

    repository.elasticsearch:
        class: SleeperBundle\Infrastructure\Repository\ElasticsearchSleepRepository

    http.client:
        class: 'SleeperBundle\Infrastructure\HttpClient'

    http.fake_client:
        class: 'SleeperBundle\Infrastructure\FakeHttpClient'

    # implicit specification of what kind of repo I need here.
    # for tests it's overwritten with fake client
    SleeperBundle\Infrastructure\ElasticsearchGateway:
        arguments:
            - '@http.client'
