services:

    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    SleeperBundle\:
        resource: '../../../../src/SleeperBundle/*'
        exclude: '../../../../src/SleeperBundle/Domain/Model'

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    SleeperBundle\Application\Controller\:
        resource: '../../../../src/SleeperBundle/Application/Controller'
        tags: ['controller.service_arguments']

    repository.doctrine:
        class: SleeperBundle\Infrastructure\Repository\DoctrineSleepRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - "SleeperBundle:SleepEntity"

    repository.in_memory:
        class: SleeperBundle\Infrastructure\Repository\InMemorySleepRepository

    # implicit specification of what kind of repo I need here.
    # for tests it's overwritten with inMemoryRepo
    SleeperBundle\Application\Service\SleepService:
        arguments:
            - '@repository.doctrine'