services:
    _defaults:
        autowire: true

    SleeperBundle\:
        resource: '../../../../src/SleeperBundle/*'
        exclude: '../../../../src/SleeperBundle/{Entity,Model,Exceptions,Controller/Output}'

    SleeperBundle\Repository\DatabaseSleepRepository:
        factory: ["@doctrine", getRepository]
        arguments:
            - "SleeperBundle:SleepEntity"
