version: '3'
services:

  codebase:
    build: .
    ports:
      - "8000:8000"

  # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
  elasticsearch:
    image: "elasticsearch"
    ports:
      - "9200:9200"