<?php

declare(strict_types=1);

use PHPUnit\Framework\TestCase;
use SleeperBundle\Domain\ValueObject\SleepId;

class SleepIdTest extends TestCase
{
    public function testThatSleepIdCanBeAutoGeneratedAndConvertedToString(): void
    {
        $generatedId = SleepId::generate();
        self::assertInstanceOf(SleepId::class, $generatedId);
        self::assertNotEmpty((string) $generatedId);
    }

    public function testThatIdCanBeAssignedAndConvertedToString(): void
    {
        $id = 'test-id';
        $sleepId = SleepId::createFrom($id);
        self::assertInstanceOf(SleepId::class, $sleepId);
        self::assertEquals($id, (string) $sleepId);
    }
}
